services:
  postgres:
    image: postgres:latest
    container_name: vpp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vpp
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "5466:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local